version: "3"
services: 
  backend:
    build:
      context: backend
    ports:
      - 3000:3000
    environment:
      PORT: 4000
    networks:
      - docker-network
    depends_on: 
      - mariadb

  mariadb:
    image: mariadb:10.7.1
    container_name: mariadb
    ports:
      - 3306:3306
    environment: 
      MYSQL_ROOT_PASSWORD: "124356"
      MARIADB_USER: "ismaeel"
      MARIADB_PASSWORD: "123456"
      MARIADB_DATABASE: "backend"
    networks:
      - docker-network
    volumes:
      - db-data:/data/db

networks:
  docker-network:
    driver: bridge

volumes:
  db-data:
    driver: local