version: '3.4'

x-common-variables: &common-variables
  MYSQL_ROOT_PASSWORD: 124356
  DB_USERNAME: ismaeel
  DB_PASSWORD: 123456
  DB_NAME: backend
  MARIADB_USER: ismaeel
  MARIADB_PASSWORD: 123456
  MARIADB_DATABASE: backend

services:
  backend:
    build:
      context: apps/backend
      args:
        API_KEY: 783deb90-896c-43f8-ad12-89ee7f5d8e97
        DB_USERNAME: ${DB_USERNAME}
        DB_PASSWORD: ${DB_PASSWORD}
        DB_PORT: ${DB_PORT}
        DB_HOST: mariadb
        DB_DIALECT: ${DB_DIALECT}
    ports:
      - 3000:3000
    environment:
      <<: *common-variables
      PORT: 3000
      DB_PORT: 3306
      DB_HOST: mariadb
      DB_DIALECT: mariadb
    restart: always
    networks:
      - docker-network
    depends_on: 
      - mariadb

  mariadb:
    image: mariadb:10.7.1
    container_name: mariadb
    ports:
      - 3306:3306
    environment:
      <<: *common-variables
      MARIADB_DATABASE: backend
    restart: always
    networks:
      - docker-network
    volumes:
      - db-data:/data/db

networks:
  docker-network:
    driver: bridge

volumes:
  db-data:
    driver: local